import { createFakeDocker } from '@/adapters/docker/fake-docker'
import { createMemoryFs } from '@/adapters/filesystem/memory-fs'
import { createMemoryLogger } from '@/adapters/logger/memory-logger'
import { p } from '@/test-utils/path'
import { describe, expect, it } from 'vitest'
import {
  hostSnapshotPath,
  pushSnapshotToContainer,
  snapshotAndPushFirewallAllowlist,
  snapshotSlugOf,
  writeHostSnapshot,
} from './firewall-snapshot'

describe('snapshotSlugOf', () => {
  it('combines basename with a stable hash so two same-named projects do not collide', () => {
    const a = snapshotSlugOf(p('/home/alice/code/crypto'))
    const b = snapshotSlugOf(p('/home/alice/work/crypto'))
    expect(a).not.toBe(b)
    expect(a.startsWith('crypto-')).toBe(true)
    expect(b.startsWith('crypto-')).toBe(true)
  })

  it('falls back to a generic prefix when the basename has no safe characters', () => {
    const slug = snapshotSlugOf(p('/'))
    expect(slug.startsWith('project-')).toBe(true)
  })
})

describe('writeHostSnapshot', () => {
  it('renders a sanitised allowlist to the slugged host path', async () => {
    const fs = createMemoryFs()
    await fs.mkdir(p('/proj/.devcontainer'), { recursive: true })
    await fs.writeFile(
      p('/proj/.devcontainer/firewall-allowlist.txt'),
      '# notes\ngithub.com\napi.anthropic.com  # used by claude\n',
    )

    const { entries, snapshotPath } = await writeHostSnapshot(p('/proj'), {
      fs,
      home: p('/home/alice'),
    })

    expect(entries.map((e) => e.value)).toEqual(['github.com', 'api.anthropic.com'])
    expect(snapshotPath).toBe(hostSnapshotPath(p('/home/alice'), p('/proj')))
    expect(snapshotPath.startsWith('/home/alice/.mydevc/firewalls/proj-')).toBe(true)
    const written = await fs.readFile(snapshotPath)
    // Banner present, no source comments preserved.
    expect(written).toContain('Generated by mydevc')
    expect(written).toContain('github.com\n')
    expect(written).not.toContain('# notes')
    expect(written).not.toContain('# used by claude')
    // 0o600 on the snapshot — operator-only.
    const stat = await fs.stat(snapshotPath)
    expect(stat.mode & 0o777).toBe(0o600)
  })

  it('throws CliError listing every invalid line', async () => {
    const fs = createMemoryFs()
    await fs.mkdir(p('/proj/.devcontainer'), { recursive: true })
    await fs.writeFile(
      p('/proj/.devcontainer/firewall-allowlist.txt'),
      'github.com\nevil; rm -rf /\n  bad space\n',
    )

    await expect(writeHostSnapshot(p('/proj'), { fs, home: p('/home/alice') })).rejects.toThrow(
      /2 invalid line\(s\)/,
    )
  })
})

describe('pushSnapshotToContainer', () => {
  it('mkdir -p /etc/mydevc, docker cp, then chown+chmod the destination', async () => {
    const fs = createMemoryFs()
    await fs.mkdir(p('/snap'), { recursive: true })
    await fs.writeFile(p('/snap/allow'), 'github.com\n')

    const docker = createFakeDocker({
      containers: [{ id: 'cid', state: 'running' }],
    })

    await pushSnapshotToContainer({
      containerId: 'cid',
      snapshotPath: p('/snap/allow'),
      deps: { docker },
    })

    expect(docker.execCalls).toEqual([
      { idOrName: 'cid', command: ['mkdir', '-p', '/etc/mydevc'], user: 'root', env: undefined },
      {
        idOrName: 'cid',
        command: ['chown', 'root:root', '/etc/mydevc/firewall-allowlist.txt'],
        user: 'root',
        env: undefined,
      },
      {
        idOrName: 'cid',
        command: ['chmod', '0444', '/etc/mydevc/firewall-allowlist.txt'],
        user: 'root',
        env: undefined,
      },
    ])
    expect(docker.cpCalls).toEqual([
      { source: '/snap/allow', dest: 'cid:/etc/mydevc/firewall-allowlist.txt' },
    ])
  })

  it('throws when mkdir fails', async () => {
    const docker = createFakeDocker({
      containers: [{ id: 'cid', state: 'running' }],
      execResponder: (inv) =>
        inv.command[0] === 'mkdir' ? { exitCode: 1, stderr: 'permission denied' } : undefined,
    })
    await expect(
      pushSnapshotToContainer({
        containerId: 'cid',
        snapshotPath: p('/snap/allow'),
        deps: { docker },
      }),
    ).rejects.toThrow(/mkdir.*failed.*permission denied/)
  })
})

describe('snapshotAndPushFirewallAllowlist', () => {
  it('returns undefined when the workspace has no allowlist', async () => {
    const fs = createMemoryFs()
    const docker = createFakeDocker()
    const out = await snapshotAndPushFirewallAllowlist(p('/proj'), {
      fs,
      docker,
      logger: createMemoryLogger(),
      home: p('/home/alice'),
    })
    expect(out).toBeUndefined()
  })

  it('throws when the allowlist exists but no container exists for the workspace', async () => {
    const fs = createMemoryFs()
    await fs.mkdir(p('/proj/.devcontainer'), { recursive: true })
    await fs.writeFile(p('/proj/.devcontainer/firewall-allowlist.txt'), 'github.com\n')

    const docker = createFakeDocker()
    await expect(
      snapshotAndPushFirewallAllowlist(p('/proj'), {
        fs,
        docker,
        logger: createMemoryLogger(),
        home: p('/home/alice'),
      }),
    ).rejects.toThrow(/no container was found/)
  })
})
